# Generated by Django 3.0.6 on 2020-08-08 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20200527_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_best_answer',
            field=models.BooleanField(default=False),
        ),
    ]
